version: '3'
services:
  node:
    build: .
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - VIRTUAL_HOST=example.com
      - LETSENCRYPT_HOST=example.com
      - LETSENCRYPT_EMAIL=daniel@example.com
    volumes:
      - .:/home/node
      - /home/node/node_modules
    depends_on:
      - mongo-paraat
  mongo-paraat:
    image: mongo
    restart: unless-stopped
    volumes:
      - progressive_audio_recorder_data:/data/db
    ports:
      - "27018:27017"
networks:
  default:
    external:
      name: nginx-proxy
volumes:
  progressive_audio_recorder_data:

